### ISSUE TITLE
Retrieve and Insert Twitter Data

### ISSUE THREAD

**Issue by gtstewar** [gtstewar/NBA-Web-Squad#10]
- [x] Put twitter data of NBA stars and teams into a file (top 30 players or so)
- [x] Make DB table with this info linked to the player or team table as a foreign key via Stored Procedure
- [x] Make a Python script that parses file and calls stored procedure

**Comment by jmtimper** [comment]
NBA Teams Twitter link: https://twitter.com/nba/lists/nbateams?lang=en
